### ISSUE TITLE
ChiCMaxima_Caller.r output of the test data did not contain the 12th column

### ISSUE THREAD

**Issue by poflawless** [yousra291987/ChiCMaxima#7]
Hello I use the test data and the recommended command line for generating the out_interactions.ibed

There is the command that I use:

 Rscript ChiCMaxima/ChiCMaxima_Caller.r -i /ChiCMaxima/testdata/mESrep2_chr15.ibed -o ./mESrep2 -w 20
 
and the output format is :
ID_Bait chr_Bait        start_Bait      end_Bait        Bait_name       ID_OE   chr_OE  start_OE        end_OE  OE_name N
632044  chr15   8994505 9004855 1110020G09Rik   631890  chr15   8533817 8540672 .       3
632044  chr15   8994505 9004855 1110020G09Rik   631964  chr15   8774170 8777495 .       7
 

it did not contain the 12th enrichment score,

did I miss something?

**Comment by TomSexton00** [comment]
Sorry for the manual being slightly out of date. In fact, this “enrichment score” turned out to have zero usefulness – it was not at all trustworthy as a measure of interaction score, so we removed it from the analysis. The output should indeed be 11 columns. 

We would like to stress that ChiCMaxima tries to make the minimum claims for any statistical model (since we don’t believe that it is really possible to make a reliable null background model), so the called peaks by ChiCMaxima_Caller are just binary yes/no answers. We are investigating how to call looping differences across conditions, but this is not ready yet.

**Comment by poflawless** [comment]
Thank you very much for your reply. When I found the genome biology article, it is fantastic, but due to it did not give the significant p value, it is not convient to be published,  could you please give some advice that can use the output of ChiCMaxima to be compared?

**Comment by TomSexton00** [comment]
Apologies for the delay in replying. As we say in the paper, ChICMaxima purposefully does not give p-values, because we are not confident in the "null" model being correctly predicted from the sparse CHi-C data. In this current iteration, ChICMaxima is therefore a qualitative peak caller. Quantitative analysis is our next goal!
